version: 0.2

phases:
  pre_build:
    commands:
      - export CURRENT_DATE=`date +"%FT%H%M"`
      - export IMAGE_TAG=`cat package.json  | grep version | awk -F "\"" '{print $4}'`
      - echo ${CURRENT_DATE}
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the project
      - docker build --build-arg CURRENT_DATE=${CURRENT_DATE} --build-arg CURRENT_VERSION=${IMAGE_TAG} -t itw-ui:${IMAGE_TAG} .
      - docker tag itw-ui:${IMAGE_TAG} 405342700223.dkr.ecr.eu-central-1.amazonaws.com/itw-ui:${IMAGE_TAG}
      - docker tag itw-ui:${IMAGE_TAG} 405342700223.dkr.ecr.eu-central-1.amazonaws.com/itw-ui:${CURRENT_DATE}
      - docker tag itw-ui:${IMAGE_TAG} 405342700223.dkr.ecr.eu-central-1.amazonaws.com/itw-ui:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 405342700223.dkr.ecr.eu-central-1.amazonaws.com/itw-ui:${IMAGE_TAG}
      - docker push 405342700223.dkr.ecr.eu-central-1.amazonaws.com/itw-ui:${CURRENT_DATE}
      - docker push 405342700223.dkr.ecr.eu-central-1.amazonaws.com/itw-ui:latest
